version: '2'
services:
  jenkins:
    # image: 'bitnami/jenkins:2'
    # user: user
    # password: bitnami
    build: .
    privileged: true
    volumes:
      - 'jenkins_data:/bitnami'
      - '/var/run/docker.sock:/var/run/docker.sock'
    network_mode: host
volumes:
  jenkins_data:
    driver: local
